#!/usr/bin/env bash
# this script uses a while loop chained with IFS to dissemble the /etc/passwd and returns paragraphs of their stories

while IFS=: read -r username password uid gid info home shell
do
    echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $info"
done < /etc/passwd
