#!/usr/bin/env bash
# I initiated the first variable "count" and then passed it into the while condition to check if it is below or equal to 10 and then print "Best School" and finally increment so that it reaches that condition to stop
count=1
while ((count<=10)); do
      echo "Best School"
      ((count++))
done