#!/usr/bin/env bash
# In this script i am using 2 nested loops to work on that clock task

hour=0
while (( hour<=12 )); do
    echo "Hour: $hour"

    minute=1
    while (( minute<=59 )); do
	echo "$minute"

	(( minute++ ))
    done

    (( hour++ ))
done
